apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aihorizontalscalers.kaiscaler.io
spec:
  group: kaiscaler.io
  names:
    kind: AIHorizontalScaler
    plural: aihorizontalscalers
    singular: aihorizontalscaler
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                minReplicas:
                  type: integer
                maxReplicas:
                  type: integer
                targetCPUUtilization:
                  type: integer
                targetMemoryUtilization:
                  type: integer
                predictionModel:
                  type: string