apiVersion: v1
kind: Service
metadata:
  name: kaiscaler-service
spec:
  selector:
    app: kaiscaler
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}