apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaiscaler-operator
  namespace: kaiscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaiscaler
  template:
    metadata:
      labels:
        app: kaiscaler
    spec:
      serviceAccountName: kaiscaler-operator-sa
      containers:
        - name: kaiscaler
          image: myrepo/kaiscaler:latest
          env:
            - name: PROMETHEUS_URL
              value: "http://prometheus-server"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi