apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaiscaler-operator-sa
  namespace: kaiscaler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kaiscaler
  name: kaiscaler-operator-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["kaiscaler.io"]
    resources: ["aihorizontalscalers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaiscaler-operator-rolebinding
  namespace: kaiscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kaiscaler-operator-role
subjects:
  - kind: ServiceAccount
    name: kaiscaler-operator-sa
    namespace: kaiscaler