apiVersion: v2
name: kaiscaler
version: 0.1.0
description: A Helm chart for KAIScaler - AI-Driven Kubernetes Autoscaler

dependencies:
  - name: prometheus
    version: "^15.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"

sources:
  - https://github.com/pirate0071/kaiscaler

maintainers:
  - name: Montassar Smida
    email: m.smida@kaiscaler.io

documentation:
  - https://kaiscaler.io/docs